# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
        migrations.AddField(
            model_name='song',
            name='channel',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='video_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
