# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikplay', '0002_auto_20180312_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'get_latest_by': 'position', 'ordering': ['position']},
        ),
    ]
