# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikplay', '0003_auto_20180314_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.TextField(default=''),
        ),
    ]
