# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiltacam', '0002_auto_20180327_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='token',
            field=models.CharField(default='empty', max_length=15),
            preserve_default=False,
        ),
    ]
